<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE planner [
    <!ELEMENT planner (year+)>
    <!ELEMENT year (date+)>
    <!ATTLIST year value CDATA #REQUIRED>
    <!ELEMENT date (node)>
    <!ATTLIST date month CDATA #REQUIRED>
    <!ATTLIST date day CDATA #REQUIRED>
    <!ELEMENT node (#PCDATA)>
]>
<planner>
    <year value="2024">
        <date month="January" day="1">
            <node>Project 1</node>
        </date>
        <date month="February" day="15">
            <node>Project 2</node>
        </date>
    </year>
    <year value="2025"> 
        <date month="March" day="10">
            <node>Project 3</node>
        </date>
        <date month="April" day="20">
            <node>Project 4</node>
        </date>
    </year>
</planner>